version: "3.8"

services:
  auth-service:
    build: .
    container_name: "auth-service"
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: "mongo-db"
    ports:
      - "27017:27017"
    restart: always
