version: "3.8"

services:
  auth-service:
    build: .
    container_name: "auth-service"
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env
    depends_on:
      - auth-mongo
    environment:
      - MONGO_URI=mongodb://auth-mongo:27017

  auth-mongo:
    image: "mongo:latest"
    container_name: "auth-mongo"
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
